name: CI/CD for Strapi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Upgrade npm
      run: npm install -g npm@latest

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo apt update -y
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs
          sudo npm install -g yarn pm2
                    if [ ! -d ".git" ]; then
            git clone https://github.com/veera1016/Task2.git .
          else
            git pull origin master
          fi
          cd /home/ubuntu/Task2/src
          yarn install
          NODE_ENV=production yarn build
           if pm2 describe strapi > /dev/null; then
            pm2 restart strapi --update-env
          else
            pm2 start yarn --name strapi -- start
          fi
