name: Deploy Strapi to EC2

on:
  push:
    branches:
      - master  # Change this to main if your default branch is main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Updating and installing dependencies..."
            sudo apt-get update -y
            sudo apt-get upgrade -y
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g yarn
            sudo npm install -g pm2

            echo "Cleaning up unnecessary packages..."
            sudo apt autoremove -y

            echo "Navigating to project directory..."
            if [ ! -d "/home/ubuntu/Task2" ]; then
              git clone https://github.com/veera1016/Task2.git /home/ubuntu/Task2
            fi
            cd /home/ubuntu/Task2

            echo "Stashing local changes to .env file..."
            git stash push -m "Stashing .env changes" .env

            echo "Pulling latest changes from GitHub..."
            git pull origin master

            echo "Applying stashed changes to .env file..."
            git stash pop

            echo "Installing dependencies..."
            yarn install

            echo "Building project for production..."
            NODE_ENV=production yarn build

            echo "Setting up environment variables..."
            echo "HOST=0.0.0.0" > .env
            echo "PORT=1337" >> .env
            echo "APP_KEYS=ePukA4aExZLOQv0TctXMPsTGVFJhLZk5npWqv38H0B4=,tALPsJRTl5d9qmvA4s5ZQKsBOzPE0ldVbmZqglC5RYw=,ad89VlKKh6ZKx5KsTzTx6G7RqkXtNvFzc7dCh8PMdRo=,ZbGpJSWwB2EPYBzWoqeTuXhUHZGS6qDBgnRPhKh2oq0=" >> .env

            echo "Restarting application using PM2..."
            pm2 delete strapi || true
            pm2 start "strapi start" --name strapi --cwd /home/ubuntu/Task2 --update-env

            echo "Checking PM2 logs..."
            pm2 logs strapi

            echo "Setting up PM2 to start on boot..."
            pm2 save
            sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ${{ secrets.EC2_USER }} --hp /home/${{ secrets.EC2_USER }}

            echo "Deployment completed successfully!"
          EOF
