name: CI/CD for Strapi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Upgrade npm
      run: npm install -g npm@latest

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            sudo apt update -y
            sudo apt upgrade -y
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt install -y nodejs
            sudo npm install -g yarn
            sudo npm install -g pm2

            # Navigate to the project directory
            if [ ! -d "/home/ubuntu/Task2" ]; then
              git clone https://github.com/veera1016/Task2.git /home/ubuntu/Task2
            fi
            cd /home/ubuntu/Task2/src

            # Pull the latest changes from the GitHub repository
            git pull origin master

            # Install dependencies
            yarn install

            # Build the project for production
            NODE_ENV=production yarn build

            # Start the application using PM2
            pm2 restart strapi || pm2 start yarn --name strapi -- start

            # Ensure PM2 restarts on reboot
            pm2 save
            sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ${{ secrets.EC2_USER }} --hp /home/${{ secrets.EC2_USER }}
          
