name: Deploy Strapi to EC2

on:
  push:
    branches:
      - master  # Change this to main if your default branch is main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Updating and installing dependencies..."
            sudo apt-get update -y
            sudo apt-get upgrade -y
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g yarn
            sudo npm install -g pm2


            echo "Cleaning up unnecessary packages..."
            sudo apt autoremove -y

            echo "Navigating to project directory..."
            if [ ! -d "/home/ubuntu/Task2" ]; then
              git clone https://github.com/veera1016/Task2.git /home/ubuntu/Task2
            fi
            cd /home/ubuntu/Task2

            echo "Pulling latest changes from GitHub..."
            git pull origin master

            echo "Building project for production..."
            NODE_ENV=production yarn build

            yarn start

            echo "Restarting application using PM2..."
            pm2 delete strapi || true
            pm2 start "yarn start" --name strapi --cwd /home/ubuntu/Task2

            echo "Checking PM2 logs..."
            pm2 logs strapi

            pm2 start npm --name strapi -- start
            pm2 save
            pm2 startup

          EOF
