name: CI/CD for Strapi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Upgrade npm
      run: npm install -g npm@latest

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Ensure Node.js and npm are installed
          if ! command -v node &> /dev/null; then
            echo "Node.js not found. Installing Node.js."
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
          if ! command -v npm &> /dev/null; then
            echo "npm not found. Please check Node.js installation."
            exit 1
          fi
          
          # Ensure Yarn is installed
          if ! command -v yarn &> /dev/null; then
            echo "Yarn not found. Installing Yarn."
            sudo npm install -g yarn
          fi

          # Ensure PM2 is installed
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 not found. Installing PM2."
            sudo npm install -g pm2
          fi

          # Ensure the target directory exists
          if [ ! -d "/home/***/Task2/src" ]; then
            echo "Directory /home/***/Task2/src does not exist."
            exit 1
          fi

          # Change to the target directory
          cd /home/***/Task2/src
          
          # Ensure the directory is a valid Git repository
          if [ ! -d ".git" ]; then
            echo "Not a git repository."
            exit 1
          fi

          # Pull the latest changes from the Git repository
          git pull origin master

          # Build the application
          NODE_ENV=production yarn build

          # Restart the application using PM2
          pm2 restart strapi
